### ISSUE TITLE
[Bug] View distance no stay put :(

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/F3_CA_BUB#100] opened 2022-01-30 22:26 UTC
**Describe the bug**
![](https://cdn.discordapp.com/attachments/782961696418562059/937473146901135400/unknown.png)

**To Reproduce**
1. Go to 'CA player'
2. Click on 'head'
3. Scroll down to 'Immersive Revive'

**Expected behavior**
Framework-set view distance stays set even if player is bonked.

**Screenshots**
https://cdn.discordapp.com/attachments/782961696418562059/937473146901135400/unknown.png

**Environmental Info(please complete the following information):**
 - Repo in use.
 - CDLC not in use
 - Framework Version [v1.4.1]

**Additional context**
🍆

**Comment by Cre8or** [comment] 2022-06-08 15:25
Cannot reproduce.

Upon investigation, I found out that [ACE already restores the user's view distance when exiting spectator mode](https://github.com/acemod/ACE3/blob/master/addons/spectator/functions/fnc_ui.sqf#L184-L186). And after testing this feature both locally and on the server, I can confirm that this feature works as expected: the user's view distance is reappplied correctly upon respawning.

Closing this for now; if the issue crops up again, we'll need to collect more data to pinpoint the cause (as your 🍆 isn't much to go by, I'm afraid).

**Closed as completed by Cre8or** 2022-06-08 15:25 UTC
Labels: bug

**Comment by Bubbus** [comment] 2022-06-08 15:52
Does the view distance hold when getting in/out of vehicles w/ ACE view distance limiter turned on?  Might be that it isn't death/uncon causing it, but ACE view limit. and kennedy was misattributing it?  If it isn't that then w/e conclusively wontfix

**Comment by Cre8or** [comment] 2022-06-08 16:29
No, ACE's view distance setting supersedes the framework's. I don't know what the original requirement for our view distance limiter was (so I can't answer whether this behaviour is intentional or not), but in my opinion the current situation is far from ideal.

The framework's implementation only sets the view distance *once* upon exiting the menu. Whatever state the user sets is not cached/stored for reuse. Meanwhile, ACE's setting is somewhat less accessible (as it requires the user to go into the addon settings, which takes longer), but is consequently saved onto the user profile - and **persists across all missions.**

Right now, I see the two ways to improve the situation - both requiring a modification of the framework:
- rewrite the framework's implementation to call ACE functions/override its view distance variables, rather than setting the view distance directly (we're already dependant on ACE anyway, so we might aswell take it further)
- remove the framework's implementation altogether. Worth noting, ACE also offers more options than we do (one setting for infantry/land vehicles/aircraft view distances, respectively).

Thoughts?

**Comment by Bubbus** [comment] 2022-06-08 17:36
My read: the framework menu should be a final override.  I figure the framework menu will be the one you use during the gameplay session so it'll be a setting that most immediately caters to your experience.  It doesn't persist between sessions and i think that's just fine because then it fits a niche of the emergency "oh fuck" button.  It's much harder to navigate to ace view settings via all the clunky arma UI while you're trying to fly a helicopter.

That said, if we can make a button that navigates to the ace view options for you that would be sick.  Or, we ask CA to use a view distance menu mod like Perceptive, and then suddenly we don't even need this anymore.

https://steamcommunity.com/sharedfiles/filedetails/?id=2726071493
